// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.pizzeria.domain.users;

import org.pizzeria.domain.users.Profile;

privileged aspect Profile_Roo_JavaBean {
    
    public String Profile.getName() {
        return this.name;
    }
    
    public void Profile.setName(String name) {
        this.name = name;
    }
    
}
