// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.pizzeria.domain;

import org.pizzeria.domain.PizzeriaTable;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect PizzeriaTable_Roo_Configurable {
    
    declare @type: PizzeriaTable: @Configurable;
    
}
