// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.pizzeria.domain.products;

import org.pizzeria.domain.products.BillProducts;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect BillProducts_Roo_Configurable {
    
    declare @type: BillProducts: @Configurable;
    
}
